import type { ProjectInput } from "../schema";

const SRC = "F:\\The Alpha Room";

export default {
  slug: "the-alpha-room",
  title: "The Alpha Room",
  tier: "commission",
  chapter: "trading",
  logline:
    "A free journal and charting desk for a coach's students, fed by a self-hosted MT5 sync fleet and an edge quote relay.",
  industry: "Trading education",
  year: 2026,
  status: "live",
  role: "Full-stack developer — app, sync fleet, edge relay",
  client: "A trading coach",
  stack: [
    "Next.js",
    "TypeScript",
    "Supabase",
    "Cloudflare Workers",
    "Durable Objects",
    "Cloudflare R2",
    "Python",
    "MetaTrader 5",
    "cTrader Open API",
    "Recharts",
  ],
  screen: { poster: "/media/projects/the-alpha-room/screen.webp", loop: "/media/projects/the-alpha-room-landing/loop.mp4" },
  coldOpen: {
    type: "image",
    src: "/media/projects/the-alpha-room/dashboard.webp",
    alt: "Trading dashboard: net P&L, win rate, profit factor and balance cards, account health score, equity curve with daily P&L bars, top trades and session edge radar",
    width: 1568,
    height: 726,
    caption: "The trader’s dashboard: account health, equity curve with deposits and withdrawals separated, and session edge.",
  },
  pitch: {
    track: "trading",
    problem: "A trading coach can't see how each student is really trading until the student sends screenshots, usually too late.",
    outcome: "Students' accounts sync on their own into a journal and charting desk, and the coach sees who needs attention first.",
  },
  gallery: [
    {
      type: "image",
      src: "/media/projects/the-alpha-room-landing/screen.webp",
      alt: "AlphaVault landing page: Every trader has a leak. Yours is in the data.",
      width: 1280,
      height: 800,
      caption: "The public landing page.",
    },
    {
      type: "image",
      src: "/media/projects/the-alpha-room/app-1.webp",
      alt: "Dashboard with net P&L, win rate, account health, equity curve and session edge",
      width: 1568,
      height: 726,
      caption: "Dashboard on a live account.",
    },
    {
      type: "image",
      src: "/media/projects/the-alpha-room/app-2.webp",
      alt: "Trade journal with the insight banner, stats and the trade table",
      width: 1568,
      height: 726,
      caption: "Journal with an automatic insight.",
    },
    {
      type: "image",
      src: "/media/projects/the-alpha-room/app-3.webp",
      alt: "Analytics overview with the drawdown-shaded equity curve and best and worst days",
      width: 1568,
      height: 726,
      caption: "Analytics overview.",
    },
    {
      type: "image",
      src: "/media/projects/the-alpha-room/app-4.webp",
      alt: "Charting desk with a daily gold chart, drawing tools and a buy/sell ticket",
      width: 1568,
      height: 726,
      caption: "Charting desk with paper trading.",
    },
  ],
  spotlights: [
    { feature: "Journal with a trade drawer, daily notes, image attachments and shareable trade cards", x: 8, y: 26, label: "Journal" },
    { feature: "Live and demo leaderboards ranked by a risk-adjusted score, with weekly movement", x: 8, y: 69, label: "Leaderboards" },
    { feature: "Configurable dashboard with tick-accurate MAE/MFE and per-minute equity", x: 75, y: 52, label: "Equity and trade stats" },
  ],
  features: [
    "Automatic MT5 and cTrader sync with read-only credentials, encrypted at rest",
    "Canvas chart with paper trading, bar-replay backtests and cloud-synced drawings",
    "Configurable dashboard with tick-accurate MAE/MFE and per-minute equity",
    "Coach console: needs-attention triage, rules engine, cohorts and weekly reviews",
    "Journal with a trade drawer, daily notes, image attachments and shareable trade cards",
    "Analytics sections and an insights engine that names the best slice in a sentence",
    "Live and demo leaderboards ranked by a risk-adjusted score, with weekly movement",
    "Calculators from position size to risk of ruin and the Kelly criterion",
    "Live quotes over an edge relay, and price alerts delivered by Telegram",
    "Statement import from CSV, MT5 spreadsheets and MT5 HTML reports",
    "Live system map coloured by the same health checks that page the operator",
    "TOTP 2FA enforced in the proxy and in row-level security",
  ],
  beats: [
    {
      kind: "context",
      heading: "Pro tools, no bill",
      body: [
        "A forex coach wanted every student to have a professional journal, analytics and charting desk without paying for it. Students unlock access through the coach's affiliate programme, and the coach approves each one by hand.",
        "Trades had to sync from MT5 on their own, using read-only investor passwords, because most students trade on their phones and can't run an expert advisor. That single constraint shaped everything else: something had to log in to broker accounts on the students' behalf, around the clock, at close to zero cost.",
      ].join("\n\n"),
    },
    {
      kind: "decision",
      heading: "Make free possible",
      body: [
        "The answer is a self-hosted Python fleet on a Windows VPS: 13 workers for sync, quote harvesting, streaming, history, alerts, an economic calendar and more, run from one deploy, verify and pause control plane, and watched by 14 health checks every five minutes that page Telegram when state changes.",
        "Live quotes travel through a single Cloudflare Durable Object. Idle hibernating sockets cost nothing, the relay tells the harvester which symbols have viewers, and sharing one socket per symbol cut an eight-symbol watchlist from 11 sockets to 2. Chart history pages from Postgres into cold gzip chunks on R2, and the harvester writes only bars that actually changed.",
      ].join("\n\n"),
    },
    {
      kind: "resolution",
      heading: "A desk students use daily",
      body: [
        "Students get a 32-widget dashboard, tick-accurate excursion analysis and per-minute equity rebuilt from real ticks, seven analytics sections, 13 calculators, a leaderboard ranked by risk-adjusted score rather than raw gain, and a canvas chart with 60 indicators, 63 drawing tools, paper trading and bar-replay backtests.",
        "The coach gets a console that ranks who needs attention — rule breaches, losing runs, missing journal entries, silence — plus a rules engine and cohorts. Two-factor sign-in is enforced in the proxy and again in row-level security on every table.",
        "It shipped in 654 commits over about twelve weeks.",
      ].join("\n\n"),
    },
  ],
  metrics: [
    {
      value: "13",
      label: "VPS worker processes",
      source: `worker inventory in docs/ENGINE.md (plus one Node audit), ${SRC} (client-trading.md §1F)`,
    },
    {
      value: "14",
      label: "health checks every 5 minutes",
      source: `checks listed in docs/ENGINE.md §5 and alpha_engine/workers/monitor.py, ${SRC} (client-trading.md §1E.3, §1F)`,
    },
    {
      value: "11 → 2",
      label: "sockets for an 8-symbol watchlist",
      source: `measured after moving to one shared socket per symbol in use-live-quote.ts, ${SRC} (client-trading.md §1E.1)`,
    },
    {
      value: "60 / 63",
      label: "chart indicators / drawing tools",
      source: `indicator unions and DrawingTool union (minus cursor, crosshair, eraser) in src/lib/chart/types.ts, ${SRC} (client-trading.md §1F)`,
    },
    {
      value: "654",
      label: "commits in about 12 weeks",
      source: `git log, 2026-07-04 to 2026-09-28, ${SRC} (client-trading.md §1F)`,
    },
  ],
  links: [{ label: "AlphaVault", href: "https://www.alphavault.trade", kind: "live" }],
  order: 10,
} satisfies ProjectInput;
